title: 无欲无求
description: 记录美好生活
author: JC老师
github_username: Natushiko

# Jekyll 配置
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# 分页 (每页文章数)
paginate: 5

# 允许HTML块内解析Markdown
kramdown:
  parse_block_html: true  